# === Сборка React (Vite) ===
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install --include=dev
RUN npm install --save-dev typescript
COPY . .

RUN npm run build
# === Production сервер (Nginx) ===
FROM nginx:1.25-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
