version: "3.9"
services:
  api:
    build: .
    container_name: myfastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # пример: можно задать лог-уровень uvicorn/gunicorn
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/docs"]
      interval: 20s
      timeout: 3s
      retries: 5
  migrate:
    build: .
    command: alembic upgrade head
    depends_on:
      - api
  worker:
    build: .
    command: python -m dramatiq app.worker:broker -p 2 -t 4
    env_file:
      - .env
    depends_on:
      - api
      # - redis


    # volumes:
    #   - ./app:/app/app:ro   # в dev можно монтировать код, в prod лучше COPY

    # Если хотите именно dev-режим с --reload:
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
