"""add iin column to users

Revision ID: 75b40cfa9932
Revises: 9631a4743f73
Create Date: 2025-10-28 15:14:27.692566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b40cfa9932'
down_revision: Union[str, Sequence[str], None] = '9631a4743f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('iin', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_users_iin'), 'users', ['iin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_iin'), table_name='users')
    op.drop_column('users', 'iin')
    # ### end Alembic commands ###
