"""baseline

Revision ID: 956b7f5e4a94
Revises: 
Create Date: 2025-09-23 18:04:11.883562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956b7f5e4a94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('kabis_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'succeeded', 'failed', 'canceled', name='jobstatus'), nullable=False),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kabis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('id_book', sa.String(), nullable=True),
    sa.Column('bbk_top', sa.String(), nullable=True),
    sa.Column('bbk_tail', sa.String(), nullable=True),
    sa.Column('bbk', sa.String(), nullable=True),
    sa.Column('dept_code', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pub_info', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('subjects', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('open_url', sa.String(), nullable=True),
    sa.Column('copy_location', sa.String(), nullable=True),
    sa.Column('ab', sa.String(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kabis')
    op.drop_table('ingestion_jobs')
    op.drop_table('documents')
    # ### end Alembic commands ###
