"""Description of model changes

Revision ID: c14b1ff2d153
Revises: 7999665ab65e
Create Date: 2025-10-25 11:03:53.298545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14b1ff2d153'
down_revision: Union[str, Sequence[str], None] = '7999665ab65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('id_book', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'id_book')
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
